import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "./components/index/Mod_index";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Com Lan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </div>
  );
}
